number=input('Please enter a number :')
adjective=input('Please enter adjective :')
noun=input('Please enter noun :')
color=input('Please enter a color :a')
noun2=input('Please enter noun :')
verbendingwthing=input('Please enter a verb ending with ing  :')
adjective2=input('Please enter adjective :')
noun3=input('Please enter noun :')
adjective3=input('Please enter adjective :')
adjective4=input('Please enter adjective :')
girlname=input('Please enter girl name :')
noun4=input('Please enter noun :')
adjective5=input('Please enter adjective :')
pluralnoun=input('Please enter plural noun:')
verb=input('Please enter verb :')
adjective6=input('Please enter adjective :')
pluralnoun2=input('Please enter plural noun:')
print(f'Hidden within the Kingdom of Hyrule are {number} peices of a/an {adjective} {noun} known as the Triforce.This {color} {noun2} holds the key to defeating Ganon and {verbendingwthing} Princess Zelda. Only the heroic Link can save the day! He must use his {adjective2} {noun3} to defeat {adjective3} monsters and battle dark forces throughout the kingdom. Link will have to fight his way through the {adjective4} Woods, Lake {girlname} and the famous Death {noun4} but first, he will need to find the {adjective5} sword. Join Link as he collects {pluralnoun} that will help him {verb} his enemies. Help him as he discovers {adjective6} dungeons and explores lost {pluralnoun2}. will he be able to save the Princess in time?')